### ISSUE TITLE
The library is not working.

### ISSUE THREAD

**Issue by arnanko** [Spencer-Easton/Apps-Script-GSApp-Library#1]
Version 6 throwing the error:
Account@domain.com={expire=1438759736, token=invalid_grant: Does this user exist?

The key used is the JSON file private key. 
Is it possible that you can release the code used previously for RSAkey? 

Thanks.

**Comment by arnanko** [comment]
This is working.
Please note that the JSON Key you would have to removed the last portion of /n. 
E.g. Json Key = ...../n , removed /n

Thanks.

**Comment by Spencer-Easton** [comment]
Not sure what you mean by remove the '/n' You should use the json key exactly as downloaded from the dev console.  

Just to clarify for others:  

```
Account@domain.com={expire=1438759736, token=invalid_grant: Does this user exist?}  
```

You can't test against dummy accounts. arnanko doesn't own domain.com so he can not request a token from a domain.com user. The error "Does this user exist?" should be sufficient.  If you can think of more descriptive language let me know.
